name: Deploy to Proxmox VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Tarik Kode Terbaru
        run: |
          cd /var/www/backend-protic
          git pull origin main
          
      - name: Eksekusi Automasi Docker
        run: |
          cd /var/www/backend-protic
          docker compose exec -T app composer install --optimize-autoloader --no-dev
          docker compose exec -T app php artisan migrate --force
          docker compose exec -T app php artisan optimize:clear
          docker compose exec -T app php artisan optimize
          echo "🚀 Deployment Backend Selesai!"